//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Cybersource.Reports.Rest.SubscriptionDetailReport {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class Report {
        
        private SubscriptionPayments subscriptionPaymentsField;
        
        private string merchantIDField;
        
        private string nameField;
        
        private string reportStartDateField;
        
        private string reportEndDateField;
        
        private string versionField;
        
        /// <remarks/>
        public SubscriptionPayments SubscriptionPayments {
            get {
                return this.subscriptionPaymentsField;
            }
            set {
                this.subscriptionPaymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReportStartDate {
            get {
                return this.reportStartDateField;
            }
            set {
                this.reportStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReportEndDate {
            get {
                return this.reportEndDateField;
            }
            set {
                this.reportEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class SubscriptionPayments {
        
        private SubscriptionPayment[] subscriptionPaymentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubscriptionPayment")]
        public SubscriptionPayment[] SubscriptionPayment {
            get {
                return this.subscriptionPaymentField;
            }
            set {
                this.subscriptionPaymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class SubscriptionPayment {
        
        private BillTo billToField;
        
        private ShipTo shipToField;
        
        private PaymentMethod paymentMethodField;
        
        private PaymentData paymentDataField;
        
        private MerchantDefinedData merchantDefinedDataField;
        
        private SubscriptionDetails subscriptionDetailsField;
        
        private string payment_request_idField;
        
        private string subscription_idField;
        
        private string transaction_dateField;
        
        private string merchant_ref_numberField;
        
        private string transaction_ref_numberField;
        
        private string e_commerce_indicatorField;
        
        /// <remarks/>
        public BillTo BillTo {
            get {
                return this.billToField;
            }
            set {
                this.billToField = value;
            }
        }
        
        /// <remarks/>
        public ShipTo ShipTo {
            get {
                return this.shipToField;
            }
            set {
                this.shipToField = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethod PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public PaymentData PaymentData {
            get {
                return this.paymentDataField;
            }
            set {
                this.paymentDataField = value;
            }
        }
        
        /// <remarks/>
        public MerchantDefinedData MerchantDefinedData {
            get {
                return this.merchantDefinedDataField;
            }
            set {
                this.merchantDefinedDataField = value;
            }
        }
        
        /// <remarks/>
        public SubscriptionDetails SubscriptionDetails {
            get {
                return this.subscriptionDetailsField;
            }
            set {
                this.subscriptionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string payment_request_id {
            get {
                return this.payment_request_idField;
            }
            set {
                this.payment_request_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subscription_id {
            get {
                return this.subscription_idField;
            }
            set {
                this.subscription_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                this.transaction_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string merchant_ref_number {
            get {
                return this.merchant_ref_numberField;
            }
            set {
                this.merchant_ref_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transaction_ref_number {
            get {
                return this.transaction_ref_numberField;
            }
            set {
                this.transaction_ref_numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string e_commerce_indicator {
            get {
                return this.e_commerce_indicatorField;
            }
            set {
                this.e_commerce_indicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class BillTo {
        
        private string customer_firstnameField;
        
        private string customer_lastnameField;
        
        private string bill_address1Field;
        
        private string bill_address2Field;
        
        private string bill_cityField;
        
        private string bill_stateField;
        
        private string bill_zipField;
        
        private string bill_countryField;
        
        private string company_nameField;
        
        private string customer_emailField;
        
        private string customer_phoneField;
        
        private string customer_ipaddressField;
        
        private string customer_account_idField;
        
        /// <remarks/>
        public string customer_firstname {
            get {
                return this.customer_firstnameField;
            }
            set {
                this.customer_firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string customer_lastname {
            get {
                return this.customer_lastnameField;
            }
            set {
                this.customer_lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string bill_address1 {
            get {
                return this.bill_address1Field;
            }
            set {
                this.bill_address1Field = value;
            }
        }
        
        /// <remarks/>
        public string bill_address2 {
            get {
                return this.bill_address2Field;
            }
            set {
                this.bill_address2Field = value;
            }
        }
        
        /// <remarks/>
        public string bill_city {
            get {
                return this.bill_cityField;
            }
            set {
                this.bill_cityField = value;
            }
        }
        
        /// <remarks/>
        public string bill_state {
            get {
                return this.bill_stateField;
            }
            set {
                this.bill_stateField = value;
            }
        }
        
        /// <remarks/>
        public string bill_zip {
            get {
                return this.bill_zipField;
            }
            set {
                this.bill_zipField = value;
            }
        }
        
        /// <remarks/>
        public string bill_country {
            get {
                return this.bill_countryField;
            }
            set {
                this.bill_countryField = value;
            }
        }
        
        /// <remarks/>
        public string company_name {
            get {
                return this.company_nameField;
            }
            set {
                this.company_nameField = value;
            }
        }
        
        /// <remarks/>
        public string customer_email {
            get {
                return this.customer_emailField;
            }
            set {
                this.customer_emailField = value;
            }
        }
        
        /// <remarks/>
        public string customer_phone {
            get {
                return this.customer_phoneField;
            }
            set {
                this.customer_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string customer_ipaddress {
            get {
                return this.customer_ipaddressField;
            }
            set {
                this.customer_ipaddressField = value;
            }
        }
        
        /// <remarks/>
        public string customer_account_id {
            get {
                return this.customer_account_idField;
            }
            set {
                this.customer_account_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class ShipTo {
        
        private string ship_to_firstnameField;
        
        private string bill_address1Field;
        
        private string ship_to_lastnameField;
        
        private string ship_to_address1Field;
        
        private string ship_to_address2Field;
        
        private string ship_to_cityField;
        
        private string ship_to_stateField;
        
        private string ship_to_zipField;
        
        private string ship_to_countryField;
        
        private string ship_to_company_nameField;
        
        /// <remarks/>
        public string ship_to_firstname {
            get {
                return this.ship_to_firstnameField;
            }
            set {
                this.ship_to_firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string bill_address1 {
            get {
                return this.bill_address1Field;
            }
            set {
                this.bill_address1Field = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_lastname {
            get {
                return this.ship_to_lastnameField;
            }
            set {
                this.ship_to_lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_address1 {
            get {
                return this.ship_to_address1Field;
            }
            set {
                this.ship_to_address1Field = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_address2 {
            get {
                return this.ship_to_address2Field;
            }
            set {
                this.ship_to_address2Field = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_city {
            get {
                return this.ship_to_cityField;
            }
            set {
                this.ship_to_cityField = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_state {
            get {
                return this.ship_to_stateField;
            }
            set {
                this.ship_to_stateField = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_zip {
            get {
                return this.ship_to_zipField;
            }
            set {
                this.ship_to_zipField = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_country {
            get {
                return this.ship_to_countryField;
            }
            set {
                this.ship_to_countryField = value;
            }
        }
        
        /// <remarks/>
        public string ship_to_company_name {
            get {
                return this.ship_to_company_nameField;
            }
            set {
                this.ship_to_company_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class PaymentMethod {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Card", typeof(Card))]
        [System.Xml.Serialization.XmlElementAttribute("Check", typeof(Check))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class Card {
        
        private string card_typeField;
        
        private string customer_cc_expmoField;
        
        private string customer_cc_expyrField;
        
        private string customer_cc_startmoField;
        
        private string customer_cc_startyrField;
        
        private string customer_cc_issuenumberField;
        
        private string account_suffixField;
        
        /// <remarks/>
        public string card_type {
            get {
                return this.card_typeField;
            }
            set {
                this.card_typeField = value;
            }
        }
        
        /// <remarks/>
        public string customer_cc_expmo {
            get {
                return this.customer_cc_expmoField;
            }
            set {
                this.customer_cc_expmoField = value;
            }
        }
        
        /// <remarks/>
        public string customer_cc_expyr {
            get {
                return this.customer_cc_expyrField;
            }
            set {
                this.customer_cc_expyrField = value;
            }
        }
        
        /// <remarks/>
        public string customer_cc_startmo {
            get {
                return this.customer_cc_startmoField;
            }
            set {
                this.customer_cc_startmoField = value;
            }
        }
        
        /// <remarks/>
        public string customer_cc_startyr {
            get {
                return this.customer_cc_startyrField;
            }
            set {
                this.customer_cc_startyrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customer_cc_issue-number")]
        public string customer_cc_issuenumber {
            get {
                return this.customer_cc_issuenumberField;
            }
            set {
                this.customer_cc_issuenumberField = value;
            }
        }
        
        /// <remarks/>
        public string account_suffix {
            get {
                return this.account_suffixField;
            }
            set {
                this.account_suffixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class Check {
        
        private string account_suffixField;
        
        private string ecp_account_typeField;
        
        private string ecp_rdfiField;
        
        /// <remarks/>
        public string account_suffix {
            get {
                return this.account_suffixField;
            }
            set {
                this.account_suffixField = value;
            }
        }
        
        /// <remarks/>
        public string ecp_account_type {
            get {
                return this.ecp_account_typeField;
            }
            set {
                this.ecp_account_typeField = value;
            }
        }
        
        /// <remarks/>
        public string ecp_rdfi {
            get {
                return this.ecp_rdfiField;
            }
            set {
                this.ecp_rdfiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class PaymentData {
        
        private string ics_applicationsField;
        
        private string recurring_payment_event_amountField;
        
        private string payment_processorField;
        
        private string currency_codeField;
        
        private string reason_codeField;
        
        private string auth_rcodeField;
        
        private string auth_codeField;
        
        private string auth_typeField;
        
        private string auth_auth_avsField;
        
        private string auth_auth_responseField;
        
        private string auth_cavv_responseField;
        
        private string ics_rcodeField;
        
        private string ics_rflagField;
        
        private string ics_rmsgField;
        
        private string request_tokenField;
        
        /// <remarks/>
        public string ics_applications {
            get {
                return this.ics_applicationsField;
            }
            set {
                this.ics_applicationsField = value;
            }
        }
        
        /// <remarks/>
        public string recurring_payment_event_amount {
            get {
                return this.recurring_payment_event_amountField;
            }
            set {
                this.recurring_payment_event_amountField = value;
            }
        }
        
        /// <remarks/>
        public string payment_processor {
            get {
                return this.payment_processorField;
            }
            set {
                this.payment_processorField = value;
            }
        }
        
        /// <remarks/>
        public string currency_code {
            get {
                return this.currency_codeField;
            }
            set {
                this.currency_codeField = value;
            }
        }
        
        /// <remarks/>
        public string reason_code {
            get {
                return this.reason_codeField;
            }
            set {
                this.reason_codeField = value;
            }
        }
        
        /// <remarks/>
        public string auth_rcode {
            get {
                return this.auth_rcodeField;
            }
            set {
                this.auth_rcodeField = value;
            }
        }
        
        /// <remarks/>
        public string auth_code {
            get {
                return this.auth_codeField;
            }
            set {
                this.auth_codeField = value;
            }
        }
        
        /// <remarks/>
        public string auth_type {
            get {
                return this.auth_typeField;
            }
            set {
                this.auth_typeField = value;
            }
        }
        
        /// <remarks/>
        public string auth_auth_avs {
            get {
                return this.auth_auth_avsField;
            }
            set {
                this.auth_auth_avsField = value;
            }
        }
        
        /// <remarks/>
        public string auth_auth_response {
            get {
                return this.auth_auth_responseField;
            }
            set {
                this.auth_auth_responseField = value;
            }
        }
        
        /// <remarks/>
        public string auth_cavv_response {
            get {
                return this.auth_cavv_responseField;
            }
            set {
                this.auth_cavv_responseField = value;
            }
        }
        
        /// <remarks/>
        public string ics_rcode {
            get {
                return this.ics_rcodeField;
            }
            set {
                this.ics_rcodeField = value;
            }
        }
        
        /// <remarks/>
        public string ics_rflag {
            get {
                return this.ics_rflagField;
            }
            set {
                this.ics_rflagField = value;
            }
        }
        
        /// <remarks/>
        public string ics_rmsg {
            get {
                return this.ics_rmsgField;
            }
            set {
                this.ics_rmsgField = value;
            }
        }
        
        /// <remarks/>
        public string request_token {
            get {
                return this.request_tokenField;
            }
            set {
                this.request_tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class MerchantDefinedData {
        
        private string merchant_defined_data1Field;
        
        private string merchant_defined_data2Field;
        
        private string merchant_defined_data3Field;
        
        private string merchant_defined_data4Field;
        
        /// <remarks/>
        public string merchant_defined_data1 {
            get {
                return this.merchant_defined_data1Field;
            }
            set {
                this.merchant_defined_data1Field = value;
            }
        }
        
        /// <remarks/>
        public string merchant_defined_data2 {
            get {
                return this.merchant_defined_data2Field;
            }
            set {
                this.merchant_defined_data2Field = value;
            }
        }
        
        /// <remarks/>
        public string merchant_defined_data3 {
            get {
                return this.merchant_defined_data3Field;
            }
            set {
                this.merchant_defined_data3Field = value;
            }
        }
        
        /// <remarks/>
        public string merchant_defined_data4 {
            get {
                return this.merchant_defined_data4Field;
            }
            set {
                this.merchant_defined_data4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://ebc.cybersource.com/ebc/reports/dtd/sdr.dtd", IsNullable=false)]
    public partial class SubscriptionDetails {
        
        private string recurring_payment_amountField;
        
        private string subscription_typeField;
        
        private string subscription_titleField;
        
        private string last_subscription_statusField;
        
        private string subscription_statusField;
        
        private string subscription_payment_methodField;
        
        private string recurring_start_dateField;
        
        private string next_scheduled_dateField;
        
        private string event_retry_countField;
        
        private string payments_successField;
        
        private string payment_success_amountField;
        
        private string recurring_number_of_paymentsField;
        
        private string installment_sequenceField;
        
        private string installment_total_countField;
        
        private string recurring_frequencyField;
        
        private string recurring_approval_requiredField;
        
        private string recurring_payment_event_approved_byField;
        
        private string recurring_automatic_renewField;
        
        private string commentsField;
        
        private string setup_feeField;
        
        private string setup_fee_currencyField;
        
        private string tax_amountField;
        
        private string merchant_secure_data1Field;
        
        private string merchant_secure_data2Field;
        
        private string merchant_secure_data3Field;
        
        private string merchant_secure_data4Field;
        
        /// <remarks/>
        public string recurring_payment_amount {
            get {
                return this.recurring_payment_amountField;
            }
            set {
                this.recurring_payment_amountField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_type {
            get {
                return this.subscription_typeField;
            }
            set {
                this.subscription_typeField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_title {
            get {
                return this.subscription_titleField;
            }
            set {
                this.subscription_titleField = value;
            }
        }
        
        /// <remarks/>
        public string last_subscription_status {
            get {
                return this.last_subscription_statusField;
            }
            set {
                this.last_subscription_statusField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_status {
            get {
                return this.subscription_statusField;
            }
            set {
                this.subscription_statusField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_payment_method {
            get {
                return this.subscription_payment_methodField;
            }
            set {
                this.subscription_payment_methodField = value;
            }
        }
        
        /// <remarks/>
        public string recurring_start_date {
            get {
                return this.recurring_start_dateField;
            }
            set {
                this.recurring_start_dateField = value;
            }
        }
        
        /// <remarks/>
        public string next_scheduled_date {
            get {
                return this.next_scheduled_dateField;
            }
            set {
                this.next_scheduled_dateField = value;
            }
        }
        
        /// <remarks/>
        public string event_retry_count {
            get {
                return this.event_retry_countField;
            }
            set {
                this.event_retry_countField = value;
            }
        }
        
        /// <remarks/>
        public string payments_success {
            get {
                return this.payments_successField;
            }
            set {
                this.payments_successField = value;
            }
        }
        
        /// <remarks/>
        public string payment_success_amount {
            get {
                return this.payment_success_amountField;
            }
            set {
                this.payment_success_amountField = value;
            }
        }
        
        /// <remarks/>
        public string recurring_number_of_payments {
            get {
                return this.recurring_number_of_paymentsField;
            }
            set {
                this.recurring_number_of_paymentsField = value;
            }
        }
        
        /// <remarks/>
        public string installment_sequence {
            get {
                return this.installment_sequenceField;
            }
            set {
                this.installment_sequenceField = value;
            }
        }
        
        /// <remarks/>
        public string installment_total_count {
            get {
                return this.installment_total_countField;
            }
            set {
                this.installment_total_countField = value;
            }
        }
        
        /// <remarks/>
        public string recurring_frequency {
            get {
                return this.recurring_frequencyField;
            }
            set {
                this.recurring_frequencyField = value;
            }
        }
        
        /// <remarks/>
        public string recurring_approval_required {
            get {
                return this.recurring_approval_requiredField;
            }
            set {
                this.recurring_approval_requiredField = value;
            }
        }
        
        /// <remarks/>
        public string recurring_payment_event_approved_by {
            get {
                return this.recurring_payment_event_approved_byField;
            }
            set {
                this.recurring_payment_event_approved_byField = value;
            }
        }
        
        /// <remarks/>
        public string recurring_automatic_renew {
            get {
                return this.recurring_automatic_renewField;
            }
            set {
                this.recurring_automatic_renewField = value;
            }
        }
        
        /// <remarks/>
        public string comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public string setup_fee {
            get {
                return this.setup_feeField;
            }
            set {
                this.setup_feeField = value;
            }
        }
        
        /// <remarks/>
        public string setup_fee_currency {
            get {
                return this.setup_fee_currencyField;
            }
            set {
                this.setup_fee_currencyField = value;
            }
        }
        
        /// <remarks/>
        public string tax_amount {
            get {
                return this.tax_amountField;
            }
            set {
                this.tax_amountField = value;
            }
        }
        
        /// <remarks/>
        public string merchant_secure_data1 {
            get {
                return this.merchant_secure_data1Field;
            }
            set {
                this.merchant_secure_data1Field = value;
            }
        }
        
        /// <remarks/>
        public string merchant_secure_data2 {
            get {
                return this.merchant_secure_data2Field;
            }
            set {
                this.merchant_secure_data2Field = value;
            }
        }
        
        /// <remarks/>
        public string merchant_secure_data3 {
            get {
                return this.merchant_secure_data3Field;
            }
            set {
                this.merchant_secure_data3Field = value;
            }
        }
        
        /// <remarks/>
        public string merchant_secure_data4 {
            get {
                return this.merchant_secure_data4Field;
            }
            set {
                this.merchant_secure_data4Field = value;
            }
        }
    }
}
